### ISSUE TITLE
TypeError: Assignment to constant variable

### ISSUE THREAD

**Issue by chungwong** [ZachSaucier/Just-Read#350]
**Describe the bug**
```
Error handling response: TypeError: Assignment to constant variable.
    at getContainer (chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:669:16)
    at createSimplifiedOverlay (chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:2369:33)
    at getDomainSelectors (chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:2343:9)
    at continueLoading (chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:2798:5)
    at afterPremium (chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:890:5)
    at chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:831:13
```
**To Reproduce**
1. Simply Enabling **Just Read**

**Env:**
 - Win 10
 - Chrome 
 - Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by ZachSaucier** [comment]
Hey chungwong and thanks for the report. This issue should only happen on pages where there are no paragraph tags in the entire document. It will be fixed in the next version which I can push live today.
