### ISSUE TITLE
Gradient color stopped working after changing color

### ISSUE THREAD

**Issue by xhw1** [ZachSaucier/Just-Read#372]
> Thanks for wanting to help improve Just Read! 
> 
> Please look through [the frequently asked questions](https://github.com/ZachSaucier/Just-Read#faq) and [the existing issues](https://github.com/ZachSaucier/Just-Read/issues?utf8=%E2%9C%93&q=is%3Aissue+) to make sure you're not asking what has already been discussed elsewhere.
> 
> Please delete this text from your post before posting.

**Describe the bug**
Gradient color stopped working.

**To Reproduce**
1. Go to Configuration
2. change "Gradient text colors to use: "
3. Save style changes
4. open a new page and turn on Just Read
5. gradient color doesn't work

**Expected behavior**
gradient color works

**Screenshots**

**Please complete the following information:**

**Additional context**

saw this error in Console 

```
Error handling response: ReferenceError: grdTxtObj is not defined
    at finishLoading (chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:2859:26)
    at doStuff (chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:2769:9)
    at createSimplifiedOverlay (chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:2776:9)
    at getDomainSelectors (chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:2351:9)
    at continueLoading (chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:2808:5)
    at afterPremium (chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:898:5)
    at chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:839:13
```

**Comment by ZachSaucier** [comment]
Good catch! Thanks for reporting. I fixed this error and am uploading a new version now.
